AllCops:
  TargetRubyVersion: 2.7 # Adjust this to match your Ruby version
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes
  AutoCorrect: true
