AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 20

Metrics/ModuleLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 7

Metrics/CyclomaticComplexity:
  Max: 7

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Naming/VariableName:
  MinNameLength: 3

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/RedundantWithIndex:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
