name: Dependency Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-dependency:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Check if dependent PR is merged
      id: check_pr
      run: |
        DEPENDENT_PR_NUMBER=$(cat .github/dependent_pr_number.txt)
        DEPENDENT_PR_STATE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/${{ github.repository }}/pulls/$DEPENDENT_PR_NUMBER | jq -r .state)

        if [ "$DEPENDENT_PR_STATE" != "closed" ]; then
          echo "The dependent PR #$DEPENDENT_PR_NUMBER is not merged yet."
          exit 1
        fi

    - name: Approve PR if dependency is merged
      uses: hmarr/auto-approve-action@v2
      if: success()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
